# Generated by Django 4.0 on 2022-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_house_image2_remove_house_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='then', verbose_name='image1'),
        ),
    ]
