# Generated by Django 4.0 on 2022-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_house_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='video',
            field=models.FileField(null=True, upload_to='then'),
        ),
    ]
