# Generated by Django 4.0 on 2022-08-05 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_house_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image1',
        ),
        migrations.AddField(
            model_name='house',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
