# Generated by Django 4.0 on 2022-08-05 11:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_house_video_house_video1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='video1',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
