# Generated by Django 4.0 on 2022-08-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_house_video1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='video1',
            new_name='video',
        ),
    ]
